AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: ./
      Description: Call the AWS Lambda API
      Timeout: 10
      # F2unctioaddn's execution role.
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonDynamoDBFullAccess
      VpcConfig:
        SecurityGroupIds:
          - sg-38a1b250
        SubnetIds:
          - subnet-4393920e
          - subnet-b6c906cd
          - subnet-ea3ceb82
      Tracing: Active
      Environment:
        Variables:
          AWS_REDIS_URL: shorturl.exwptz.ng.0001.aps1.cache.amazonaws.com:6379
          AWSREGION: ap-south-1

